@apiUrl = http://localhost:5000/social-media-app-fafc6/europe-west3/api

@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjIzNzA1ZmNmY2NjMTg4Njg2ZjhhZjkyYWJiZjAxYzRmMjZiZDVlODMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLW1lZGlhLWFwcC1mYWZjNiIsImF1ZCI6InNvY2lhbC1tZWRpYS1hcHAtZmFmYzYiLCJhdXRoX3RpbWUiOjE2MDIxNTU2MDAsInVzZXJfaWQiOiJuSUFKMk5vUUZqZDVHWDZIZm1vSHJBb2V4MHgxIiwic3ViIjoibklBSjJOb1FGamQ1R1g2SGZtb0hyQW9leDB4MSIsImlhdCI6MTYwMjE1NTYwMCwiZXhwIjoxNjAyMTU5MjAwLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.IMoot9nINeWRd2xO-vVTzU0W5YzPIMMY1LIpsfZ0dMruGzgl79raArv_lal-Ols3K2RU231mD2gk2vn1Mm3jgU8ms2teBhYq-cyDMZckxxS4bwh1gtrtVS67BPdbmTDFZNSNLOMkkM2GaYUgwwkqypOy9WQCrBSpZy9syAKOi4bGGI5YPOE-uOcmCTevf0fnqc5Cl-sx-PgsiDrkVOryDah5JBZwxQfGUG3Uz_zdOAMtLhR-HMaI0X3RVmW5gUJl2bra8N4mWMDA4OOxgzuLiI76IiwfEjMLhqUhYK7Pmwxf8yQkKYnsvQADLRldopVxy_Z9gF7eswX7hFPudIFrYA

@screamId =

### Get all screams
GET {{apiUrl}}/screams

### Post one scream
POST {{apiUrl}}/scream
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "body": "Hello from rest 1",
   "userHandle": "user"
}

### Create new user
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user1@gmail.com",
   "password": "123456",
   "confirmPassword": "123456",
   "handle": "user1"
}

### Create new user with empty data
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "",
   "password": "",
   "confirmPassword": "",
   "handle": ""
}

### Create new user with invalid email address
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user",
   "password": "",
   "confirmPassword": "",
   "handle": ""
}

### Create new user with different passwords
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "123456",
   "confirmPassword": "1234567",
   "handle": "user"
}

### Login user
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "123456"
}

### Login user with empty data
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "",
   "password": ""
}

### Login with wrong credentials
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "111111111111"
}

### Add user details
POST {{apiUrl}}/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "bio": "",
   "website": "google.com",
   "location": "Sofia, BG"
}

### Get user details 
GET {{apiUrl}}/user
Authorization: Bearer {{accessToken}}

### Get scream by id
GET {{apiUrl}}/scream/{{screamId}}

### Comment on scream
POST {{apiUrl}}/scream/{{screamId}}/comment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "body": "Comment"
}

### Like scream
GET {{apiUrl}}/scream/{{screamId}}/like
Authorization: Bearer {{accessToken}}

### Unlike scream
GET {{apiUrl}}/scream/{{screamId}}/unlike
Authorization: Bearer {{accessToken}}

### Delete scream
DELETE {{apiUrl}}/scream/{{screamId}}
Authorization: Bearer {{accessToken}}

### Get user details by handle
GET {{apiUrl}}/user/user

### Get not existing user details by handle
GET {{apiUrl}}/user/xxx

### Mark notifications read 
POST {{apiUrl}}/notifications
Authorization: Bearer {{accessToken}}
Content-Type: application/json

[
   "78teum4VRd7SpGNnBvNd"
]