@apiUrl = http://localhost:5000/social-media-app-fafc6/europe-west3/api

@accessToken = 

@screamId = 

### Get all screams
GET {{apiUrl}}/screams

### Post one scream
POST {{apiUrl}}/scream
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "body": "Hello from rest 1",
   "userHandle": "user"
}

### Post scream with empty body
POST {{apiUrl}}/scream
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "body": "",
   "userHandle": "user"
}

### Create new user
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user1@gmail.com",
   "password": "123456",
   "confirmPassword": "123456",
   "handle": "user1"
}

### Create new user with empty data
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "",
   "password": "",
   "confirmPassword": "",
   "handle": ""
}

### Create new user with invalid email address
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user",
   "password": "",
   "confirmPassword": "",
   "handle": ""
}

### Create new user with different passwords
POST {{apiUrl}}/signup
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "123456",
   "confirmPassword": "1234567",
   "handle": "user"
}

### Login user
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "123456"
}

### Login user with empty data
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "",
   "password": ""
}

### Login with wrong credentials
POST {{apiUrl}}/login
Content-Type: application/json

{
   "email": "user@gmail.com",
   "password": "111111111111"
}

### Add user details
POST {{apiUrl}}/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "bio": "",
   "website": "google.com",
   "location": "Sofia, BG"
}

### Get user details 
GET {{apiUrl}}/user
Authorization: Bearer {{accessToken}}

### Get scream by id
GET {{apiUrl}}/scream/{{screamId}}

### Comment on scream
POST {{apiUrl}}/scream/{{screamId}}/comment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "body": "Comment"
}

### Like scream
GET {{apiUrl}}/scream/{{screamId}}/like
Authorization: Bearer {{accessToken}}

### Unlike scream
GET {{apiUrl}}/scream/{{screamId}}/unlike
Authorization: Bearer {{accessToken}}

### Delete scream
DELETE {{apiUrl}}/scream/{{screamId}}
Authorization: Bearer {{accessToken}}

### Get user details by handle
GET {{apiUrl}}/user/user

### Get not existing user details by handle
GET {{apiUrl}}/user/xxx

### Mark notifications read 
POST {{apiUrl}}/notifications
Authorization: Bearer {{accessToken}}
Content-Type: application/json

[
   "78teum4VRd7SpGNnBvNd"
]